import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/Components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Envobyte",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
